steps:
  # Frontend Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'front_end/REACT-APP' # Path to frontend directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'front_end/REACT-APP' # Path to frontend directory

  # Frontend Deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '--image', 'gcr.io/famous-modem-416401/frontend-image', '--platform', 'managed', '--region', 'us-central5', '--allow-unauthenticated']
    dir: 'front_end/REACT-APP' # Path to frontend directory

  # Backend Build
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
    dir: 'back-end' # Path to backend directory

  # Backend Deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '--image', 'gcr.io/famous-modem-416401/backend-image', '--platform', 'managed', '--region', 'us-central5', '--allow-unauthenticated']
    dir: 'back-end' # Path to backend directory
